<a href="https://colab.research.google.com/github/emo7bf/rummikubSolver/blob/master/Rummikub_Board_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Rummikub Solver

In [0]:
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    COLAB = True
    print("Note: using Google CoLab")
    %tensorflow_version 2.x
except:
    print("Note: not using Google CoLab")
    COLAB = False

import base64
import os
import numpy as np
import pandas as pd
import requests
from scipy.stats import zscore
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import requests
import numpy as np
from scipy import signal
from sklearn import metrics
from matplotlib import pyplot as plt



Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
Note: using Google CoLab
TensorFlow 2.x selected.


In [0]:
import numpy as np
class boardState: #user never interacts with the node class
  # _ids = count(0)

  def __init__(self):
    # self.id = next(self._ids)
    
    # Every game starts out with a blank board, with no wilds and no tiles out
    self.board =  np.array(  [[0]*4]*13 )
    self.wild = 0

    # Eligible tiles to be drawn are: four different colors, numbers 1 thru 13, two of each, and two wild tiles
    self.todraw = [(0, 0)]*(4*2*13 + 2)

    print( len(self.todraw) )

  def showboard(self):
    plt.imshow(self.board, interpolation='nearest')
    plt.show()

  # Creates a random board state
  def randomPopulate(self):
    self.board = np.random.randint(3, size=(13, 4))

  def makeMatches(self):
    b = self.board
    # There are a finite number of different options for each number:
    # [order doesn't matter here]
    # 0 0 0 0  -- 0
    # 1 0 0 0  -- 1
    # 1 1 0 0  -- 2
    # 1 1 1 0  -- 0 (3)
    # 1 1 1 1  -- 0 (1) (4)

    # 2 0 0 0  -- 2
    # 2 1 0 0  -- 3
    # 2 2 0 0  -- 4
    # 2 1 1 0  -- 1 (4)
    # 2 2 1 0  -- 2 (5)
    # 2 2 2 0  -- 0 (3) (6)
    # 2 1 1 1  -- 1 (2) (5)
    # 2 2 1 1  -- 0 (2) (3) (6) 
    # 2 2 2 1  -- 0 (1) (3) (4) (7)


    # k1 = np.array( [[-0.5, 1, -0.5, 0]] )
    # sols1 = signal.convolve(k1, self.board)
    


    tf = (b > 0)
    k2 = np.array( [[1, 0, 0, 0]]*3 )
    display(k2)
    sols2 = signal.convolve( k2, tf )
    display( tf )
    display(sols2[:,1])
    
    # # Find the "marginals"

    # matches =  np.matmul( (b > 0), [1, 1, 1, 1] )

    # # or

    # subtract = b - [[1, 1, 1, 1]]*13
    # horzMatch = ( subtract >= 0 )

    # horzMarg = np.sum(horzMatch, axis=1)
    # display( (horzMarg == 3)*1 )
    # display( (horzMarg == 4)*1 )
    # plt.imshow(b, interpolation='nearest')
    # plt.show()
    
    # plt.imshow((sols2 == 0), interpolation='nearest')
    # plt.show()

    # plt.imshow(( (sols1 == 0) * (sols2 == 0) ), interpolation='nearest')
    # plt.show()



  def __repr__(self):
        return str(self.board)
        # return "( W: {0}, wt: {1}, inc: {2} )".format(self.W, self.wt, self.inc)

  def __str__(self):
        return str(self.board)

b = boardState()
b.randomPopulate()
display(b)
b.makeMatches()
# b.showboard()


106


[[2 2 0 1]
 [2 1 0 2]
 [1 1 2 2]
 [0 2 2 2]
 [0 1 1 1]
 [2 0 1 1]
 [2 2 0 2]
 [2 2 0 1]
 [2 2 2 1]
 [0 2 0 1]
 [1 2 0 1]
 [0 2 1 2]
 [2 1 0 2]]

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]])

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True,  True, False,  True],
       [False,  True,  True,  True],
       [ True,  True, False,  True]])

array([1, 2, 3, 3, 3, 2, 2, 2, 3, 3, 3, 3, 3, 2, 1])